### PR TITLE
Switch default font: Arial -> Liberation Sans

### PR DESCRIPTION
**Pull request by jacg**
As a very cheap, first-order solution to the issues discussed [here](https://github.com/Yatekii/qrbill/issues/7#issuecomment-2227284474).

### CODE REVIEW

**Review by Yatekii — COMMENTED** [review]
This font does not exist on macOS apparently. Why can't we have both in the list so we fall back?

**Comment by jacg** [comment]
I guess we should list all four of the allowed fonts to maximize the chance of fallback succeeding. But it's not clear to me where we would do that, and whether it would suffice (or work similarly) for both SVG and PDF. The code submitted here merely changes the *single* hard-wired choice of font.

**Comment by Yatekii** [comment]
It should be possible to provide a list of all fonts, comma separated, in that field I'd think. At least that's how HTML & CSS work.

**Comment by jacg** [comment]
Yes, that seems to be working.

**Comment by Yatekii** [comment]
Thank you, sir!

**Pull request merged**
